export const strings = {
    appName: "PDF concatenator (and splitter)",
    uploadedFiles: "Uploaded Files",
    uploadFiles: "Upload Images or PDF",
    view: "View",
    extract: "Extract",
    remove: "×",
    dragger: "⣿",
    generating: "Generating...",
    generatingPdf: "Generating PDF...",
    generatePdf: 'Generate PDF',
    generatingZip: 'Generating ZIP...',
    downloadZip: 'Download ZIP',
    noFiles: "No files uploaded yet",
    PDF: "PDF",
    pages: "pages",
    close: "Close",
    clearAll: "Clear All",
    disableGeneratePdfBecauseOfPdf: "Extract all PDF first",
    description: "A versatile online tool for working with PDF files. Combine multiple images (JPG, PNG) and PDF files into a single document, or split PDF files into separate images. No any data transferring to server, can work offline, so all your data are secured and private.",
    imageFiles: "Image Files",
    pdfFiles: "PDF Files",
    "totalFiles": "Total Files",
}