export const strings = {
    appName: "PDF concatenator (and splitter)",
    uploadedFiles: "Uploaded Files",
    uploadFiles: "Upload Images or PDF",
    view: "View",
    extract: "Extract",
    remove: "×",
    dragger: "⣿",
    generatingPdf: "Generating PDF...",
    generatePdf: 'Generate PDF',
    generatingZip: 'Generating ZIP...',
    donwloadZip: 'Download ZIP',
    noFiles: "No files uploaded yet",
    PDF: "PDF",
    pages: "pages",
    close: "Close",
    clear: "Clear files",
    disableGeneratePdfBecvauseOfPdf: "Extract all PDF first",
    description: "A versatile online tool for working with PDF files. Combine multiple images (JPG, PNG) and PDF files into a single document, or split PDF files into separate images. No any data transferring to server, can work offline, so all your data are secured and private."
}